language: generic
env:
  global:
  - RAKUDO_VERSION="2017.11"
  - NQP_VERSION="2017.11"
  - MOARVM_VERSION="2017.11"
  - REVISION="01"
  - PATH=/opt/rakudo-pkg/bin:$PATH
  - RAKUDO_DEB="https://github.com/nxadm/rakudo-pkg/releases/download/v2017.11/rakudo-pkg-Ubuntu14.04_2017.11-01_amd64.deb"
  matrix:
  - OS=alpine ARCH=amd64 VERSION=3.6
  - OS=alpine ARCH=amd64 VERSION=3.7
  - OS=centos ARCH=amd64 VERSION=7
  - OS=debian ARCH=amd64 VERSION=8
  - OS=debian ARCH=amd64 VERSION=9
  - OS=fedora ARCH=amd64 VERSION=25
  - OS=fedora ARCH=amd64 VERSION=26
  - OS=fedora ARCH=amd64 VERSION=27
  - OS=ubuntu ARCH=amd64 VERSION=14.04
  - OS=ubuntu ARCH=amd64 VERSION=16.04
  - OS=ubuntu ARCH=amd64 VERSION=17.04
  - OS=ubuntu ARCH=amd64 VERSION=17.10
  - OS=ubuntu ARCH=amd64 VERSION=14.04
  - OS=ubuntu ARCH=i386 VERSION=16.04
  - OS=ubuntu ARCH=i386 VERSION=17.04
  - OS=ubuntu ARCH=i386 VERSION=17.10
sudo: required
services:
- docker
install: wget $RAKUDO_DEB && sudo dpkg -i *.deb
script:
- bin/create-img.p6 docker/Dockerfile-${OS}-${ARCH}-${VERSION} && bin/create-pkg.p6
  rakudo-pkg/$OS-$ARCH:$VERSION --rakudo-version=$RAKUDO_VERSION --nqp-version=$NQP_VERSION
  --moarvm-version=$MOARVM_VERSION --rev=$REVISION
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: kZZIX3JLoAowpJgQXUheKMquNtnPUNa18SFQQSYaQe3OjaBLzJGuI/Dv+eju3dZA9HWXVVfAl/EBYmx0YRyIa8XPoKL+hxbl29sdcP7wNi4OJsIcYr2dY7dcPY2T1RIWCd2cU7CXbJ1IquDN67asWEBxbpwpZluYDd9odx2JMeMAf2XX+VQjFxwK92hGrpLMdtzNstSiZvYn7inBTOU8nrBxQVccd7ec9ZsF8PUjohazUzpCHYvHgZOPHQZY1UgOD1KlrUmPtUToakDOnXyysZBvC3YBq833eqBXIlaoCELnFdzOnwIQzewxYgXrz4JQQhUmXPIvmylM0MoNp1MnkANs68oECBLvOB8kxOglIYWBad6GtaR5pkLhh3bPwc6fwqZZQMoqlncesKDPtHvmtQmWpWFxbwYsOFgFDcc3jW8DV233EbpubrREbrYFq83Ahc0aYx+GpNWFZ71jlXcErZ7tB/KltHWoCjLPq1dxCIFiq/AOLylK9meo/AQF+RXAb5+3fkd32X5xyRQejYfdhGxZ/c6QkV4C3BAIypJ76Hi0MfePuylMTe4P59nkT98j6ef3d8MtPHIM8DdBww6erseteKCaS0fZaf3e3YBhG9TJYLTHri4o/StCnqTMyiANEcsNoQB3oFC3z5Q76jYHocKo5g+z/6/ooeipn03hKsA=
  file_glob: true
  file: "/var/tmp/rakudo-pkg/*"
  skip_cleanup: true
  on:
    repo: nxadm/rakudo-pkg
    tags: true
  branches:
    only:
      - /^v\d+\.\d+$/
